export const AUTH_RETRIEVE_PROFILE_STARTED = 'AUTH_RETRIEVE_PROFILE_STARTED';
export const AUTH_RETRIEVE_PROFILE_COMPLETED =
  'AUTH_RETRIEVE_PROFILE_COMPLETED';
export const AUTH_RETRIEVE_PROFILE_ERROR = 'AUTH_RETRIEVE_PROFILE_ERROR';
export const AUTH_NOT_LOGGED_IN_ERROR = 'AUTH_NOT_LOGGED_IN_ERROR';
