export const AUTH_RETRIEVE_PROFILE_STARTED = 'AUTH_RETRIEVE_PROFILE_STARTED';
export const AUTH_RETRIEVE_PROFILE_COMPLETED =
  'AUTH_RETRIEVE_PROFILE_COMPLETED';
export const AUTH_RETRIEVE_PROFILE_ERROR = 'AUTH_RETRIEVE_PROFILE_ERROR';
export const AUTH_NOT_LOGGED_IN_ERROR = 'AUTH_NOT_LOGGED_IN_ERROR';

// User wishlist actions
export const GET_USER_WISHLIST_STARTED = 'GET_USER_WISHLIST_STARTED';
export const GET_USER_WISHLIST_COMPLETE = 'GET_USER_WISHLIST_COMPLETE';
export const GET_USER_WISHLIST_ERROR = 'GET_USER_WISHLIST_ERROR';
export const CLEAR_USER_WISHLIST = 'CLEAR_USER_WISHLIST';

export const ADD_USER_WISHLIST_ITEM_STARTED = 'ADD_USER_WISHLIST_ITEM_STARTED';
export const ADD_USER_WISHLIST_ITEM_COMPLETE =
  'ADD_USER_WISHLIST_ITEM_COMPLETE';
export const ADD_USER_WISHLIST_ITEM_ERROR = 'ADD_USER_WISHLIST_ITEM_ERROR';

export const EDIT_USER_WISHLIST_ITEM_STARTED =
  'EDIT_USER_WISHLIST_ITEM_STARTED';
export const EDIT_USER_WISHLIST_ITEM_COMPLETE =
  'EDIT_USER_WISHLIST_ITEM_COMPLETE';
export const EDIT_USER_WISHLIST_ITEM_ERROR = 'EDIT_USER_WISHLIST_ITEM_ERROR';

export const DELETE_USER_WISHLIST_ITEM_STARTED =
  'DELETE_USER_WISHLIST_ITEM_STARTED';
export const DELETE_USER_WISHLIST_ITEM_COMPLETE =
  'DELETE_USER_WISHLIST_ITEM_COMPLETE';
export const DELETE_USER_WISHLIST_ITEM_ERROR =
  'DELETE_USER_WISHLIST_ITEM_ERROR';

// Public wishlists actions
export const GET_ALT_WISHLISTS_STARTED = 'GET_ALT_WISHLISTS_STARTED';
export const GET_ALT_WISHLISTS_COMPLETE = 'GET_ALT_WISHLISTS_COMPLETE';
export const GET_ALT_WISHLISTS_ERROR = 'GET_ALT_WISHLISTS_ERROR';
export const CLEAR_ALT_WISHLISTS = 'CLEAR_ALT_WISHLISTS';

export const CLAIM_ITEM_STARTED = 'CLAIM_ITEM_STARTED';
export const CLAIM_ITEM_COMPLETE = 'CLAIM_ITEM_COMPLETE';
export const CLAIM_ITEM_ERROR = 'CLAIM_ITEM_ERROR';

export const UNCLAIM_ITEM_STARTED = 'UNCLAIM_ITEM_STARTED';
export const UNCLAIM_ITEM_COMPLETE = 'UNCLAIM_ITEM_COMPLETE';
export const UNCLAIM_ITEM_ERROR = 'UNCLAIM_ITEM_ERROR';

// Claims actions
export const GET_USER_CLAIMS_STARTED = 'GET_USER_CLAIMS_STARTED';
export const GET_USER_CLAIMS_COMPLETE = 'GET_USER_CLAIMS_COMPLETE';
export const GET_USER_CLAIMS_ERROR = 'GET_USER_CLAIMS_ERROR';
export const CLEAR_USER_CLAIMS = 'CLEAR_USER_CLAIMS';
